RoleProject/Models/Agince.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNet.Identity;

namespace RoleProject.Models
{
    public class Agince
    {
        [Key]
        [Required]
        public String Agince_ID { get; set; }
        [Required]

        public string name { get; set; }

        private string Password_Agence;
        [Required]
        [DataType(DataType.Password)]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        public string password { get { return Password_Agence; } set { Password_Agence = value; } }

        //[NotMapped]
        //[Display(Name = "Confirm Password")]
        //[Compare("password", ErrorMessage = "The password and confirmation password do not match.")]
        //[DataType(DataType.Password)]

        //public string confirm_Password { get; set; }

        // collection of phone for agence
        [Display(Name =  "Phone Number")]
       
        public string phone_number { get; set; }
   
        public string city { get; set; }
    
        public string street { get; set; }
        [Display(Name ="photo of Agince")]
        public string photo_Agince { get; set; }
        [NotMapped]
        public HttpPostedFileBase photo_path { get; set; }
        // Collection of cars in Agince 
        public Collection<Car> Collection_Of_Car { get; set; }
        public virtual ApplicationUser userAccount { get; set; }
    }
}

RoleProject/Controllers/AginceController.cs
//using System;
//using System.Collections.Generic;
//using System.IO;
//using System.Linq;
//using System.Net;
//using System.Web;
//using System.Web.Mvc;
//using RoleProject.Models;

//namespace RoleProject.Controllers
//{
//    public class AginceController : Controller
//    {
//        ApplicationDbContext context = new ApplicationDbContext();
//        // GET: Agince
//        public ActionResult Index()
//        {


//            return View(context.Agince.ToList());

//        }

//        // GET: Agince/Details/5
//        public ActionResult Details(String id)
//        {
//            try
//            {
//                var Agince = context.Agince.FirstOrDefault(ag => ag.Agince_ID == id);
//                return View(Agince);
//            }
//            catch
//            {
//                return View();
//            }
//        }

//        // GET: Agince/Create
//        public ActionResult Create()
//        {
//            return View();
//        }

//        // POST: Agince/Create
//        [HttpPost]
//        public ActionResult Create(string password, Agince agince)
//        {
//            #region Old_Creat
//            //try
//            //{
//            //    agince.password = password;  
//            //    /*Add photo to Data Base*/
//            //    string filename = Path.GetFileNameWithoutExtension(agince.photo_path.FileName);
//            //    string Extintion = Path.GetExtension(agince.photo_path.FileName);
//            //    filename = filename + DateTime.Now.ToString("yymmssfff") + Extintion;
//            //    agince.photo_Agince =filename;
//            //    filename = Path.Combine(Server.MapPath("~/images/"), filename);
//            //    agince.photo_path.SaveAs(filename);
//            //    //----------------------------//
//            //    context.Agince.Add(agince);
//            //    context.SaveChanges();
//            //    return RedirectToAction("Index","Home");
//            //}
//            //catch
//            //{
//            //    return View("Create");
//            //} 
//            #endregion
//            if (ModelState.IsValid)
//            {
//                /*Add photo to Data Base*/
//                string filename = Path.GetFileNameWithoutExtension(agince.photo_path.FileName);
//                string Extintion = Path.GetExtension(agince.photo_path.FileName);
//                filename = filename + DateTime.Now.ToString("yymmssfff") + Extintion;
//                agince.photo_Agince = filename;
//                filename = Path.Combine(Server.MapPath("~/images/"), filename);
//                agince.photo_path.SaveAs(filename);
//                //----------------------------//
//                context.Agince.Add(agince);
//                context.SaveChanges();
//                return RedirectToAction("Index");
//            }

//            return View(agince);
//        }

//        // GET: Agince/Edit/5
//        public ActionResult Edit(string id)
//        {

//            if (id == null)
//            {
//                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
//            }
//            Agince aganis_Car = context.Agince.Find(id);
//            if (aganis_Car == null)
//            {
//                return HttpNotFound();
//            }
//            return View(aganis_Car);

//        }
//        // POST: Agince/Edit/5
//        [HttpPost]
//        public ActionResult Edit(String id, Agince agince, string password)
//        {

//            try
//            {
//                var newAgince = context.Agince.FirstOrDefault(agince_ => agince_.Agince_ID == id);

//                if (newAgince.password == password)
//                {
//                    newAgince.password = password;
//                    newAgince.confirm_Password = password;
//                    newAgince.name = agince.name;
//                    newAgince.phone_number = agince.phone_number;
//                    /*Add photo to Data Base*/
//                    string filename = Path.GetFileNameWithoutExtension(agince.photo_path.FileName);
//                    string Extintion = Path.GetExtension(agince.photo_path.FileName);
//                    filename = filename + DateTime.Now.ToString("yymmssfff") + Extintion;
//                    newAgince.photo_Agince = filename;
//                    filename = Path.Combine(Server.MapPath("~/images/"), filename);
//                    agince.photo_path.SaveAs(filename);
//                    //----------------------------//
//                }
//                else
//                {
//                    return View("Edit");
//                }


//                context.SaveChanges();
//                return RedirectToAction("Index");
//            }
//            catch
//            {
//                return View("Edit");
//            }
//        }

//        // GET: Agince/Delete/5
//        public ActionResult Delete(string id)
//        {
//            var Deleted_Agince = context.Agince.FirstOrDefault(agince_ => agince_.Agince_ID == id);
//            return View(Deleted_Agince);
//        }

//        // POST: Agince/Delete/5
//        [HttpPost]
//        public ActionResult Delete(String id)
//        {
//            try
//            {

//                var Deleted_Agince = context.Agince.FirstOrDefault(agince_ => agince_.Agince_ID == id);
//                context.Agince.Remove(Deleted_Agince);
//                context.SaveChanges();
//                return RedirectToAction("Index");
//            }
//            catch
//            {
//                return View();
//            }
//        }
//    }
//}

RoleProject/Controllers/AgincesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RoleProject.Models;

namespace RoleProject.Controllers
{
    public class AgincesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Aginces
        public ActionResult List_Of_All()
        {
            return View(db.Agince.ToList());
        }

        // GET: Aginces/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agince agince = db.Agince.Find(id);
            if (agince == null)
            {
                return HttpNotFound();
            }
            return View(agince);
        }

        // GET: Aginces/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Aginces/Create
     
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( Agince agince)
        {
            if (ModelState.IsValid)
            {
                //string filename = Path.GetFileNameWithoutExtension(agince.photo_path.FileName);
                //string Extintion = Path.GetExtension(agince.photo_path.FileName);
                //filename = filename + DateTime.Now.ToString("yymmssfff") + Extintion;
                //agince.photo_Agince = filename;
                //filename = Path.Combine(Server.MapPath("~/images/"), filename);
                //agince.photo_path.SaveAs(filename);

                db.Agince.Add(agince);
                db.SaveChanges();
                return RedirectToAction("List_Of_All");
            }

            return View(agince);
        }

        // GET: Aginces/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agince agince = db.Agince.Find(id);
            if (agince == null)
            {
                return HttpNotFound();
            }
            return View(agince);
        }

        // POST: Aginces/Edit/5
      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( Agince agince)
        {
            if (ModelState.IsValid)
            {
                string filename = Path.GetFileNameWithoutExtension(agince.photo_path.FileName);
                string Extintion = Path.GetExtension(agince.photo_path.FileName);
                filename = filename + DateTime.Now.ToString("yymmssfff") + Extintion;
                agince.photo_Agince = filename;
                filename = Path.Combine(Server.MapPath("~/images/"), filename);
                agince.photo_path.SaveAs(filename);


                db.Entry(agince).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("List_Of_All");
            }
            return View(agince);
        }

        // GET: Aginces/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agince agince = db.Agince.Find(id);
            if (agince == null)
            {
                return HttpNotFound();
            }
            return View(agince);
        }

        // POST: Aginces/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Agince agince = db.Agince.Find(id);
            db.Agince.Remove(agince);
            db.SaveChanges();
            return RedirectToAction("List_Of_All");
        }

      
    }
}

RoleProject/Views/Aginces/Create.cshtml
@model RoleProject.Models.Agince

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm(@*"Create", "Aginces", FormMethod.Post, new { enctype = "multipart/form-data" }*@))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Agince</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Agince_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Agince_ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Agince_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phone_number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phone_number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phone_number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.city, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.city, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.city, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.street, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.street, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.street, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.photo_Agince, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.photo_Agince, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.photo_Agince, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.photo_path, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="photo_path" id="photo_path" />

            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "List_Of_All")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RoleProject/Views/Aginces/Delete.cshtml
@model RoleProject.Models.Agince

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Agince</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phone_number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phone_number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.city)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.city)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.street)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.street)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.photo_Agince)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.photo_Agince)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "List_Of_All")
        </div>
    }
</div>

RoleProject/Views/Aginces/Details.cshtml
@model RoleProject.Models.Agince

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Agince</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phone_number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phone_number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.city)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.city)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.street)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.street)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.photo_Agince)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.photo_Agince)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Agince_ID }) |
    @Html.ActionLink("Back to List", "List_Of_All")
</p>

RoleProject/Views/Aginces/Edit.cshtml
@model RoleProject.Models.Agince

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Aginces", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Agince</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Agince_ID)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phone_number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phone_number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phone_number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.city, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.city, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.city, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.street, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.street, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.street, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.photo_Agince, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.photo_Agince, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.photo_Agince, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.photo_path, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="photo_path" id="photo_path" />

            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "List_Of_All")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RoleProject/Views/Aginces/List_Of_All.cshtml
@model IEnumerable<RoleProject.Models.Agince>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.password)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.phone_number)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.city)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.street)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.photo_Agince)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.password)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.phone_number)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.city)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.street)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.photo_Agince)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Agince_ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.Agince_ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Agince_ID })
        </td>
    </tr>
}

</table>